// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new workspace with the specified root directory.
 * 
 * # Arguments
 * * `root_dir` - Path to the workspace root directory (absolute or relative)
 * 
 * # Returns
 * * `WorkspaceSummary` - Summary of the created workspace including ID and canonicalized path
 * 
 * # Errors
 * * `ApiError::InvalidInput` - If root_dir is empty
 * * `ApiError::PathNotFound` - If the path does not exist
 * * `ApiError::PathNotDirectory` - If the path exists but is not a directory
 * * `ApiError::IoError` - If the path cannot be canonicalized
 */
async workspaceCreate(rootDir: string) : Promise<Result<WorkspaceSummary, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_create", { rootDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets the currently focused workspace.
 * 
 * # Arguments
 * * `workspace_id` - ID of the workspace to focus
 * 
 * # Returns
 * * `()` - Focus was set successfully
 * 
 * # Errors
 * * `ApiError::InvalidInput` - If workspace_id is empty
 * * `ApiError::WorkspaceNotFound` - If the workspace does not exist
 */
async workspaceSetFocus(workspaceId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_focus", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the currently focused workspace ID.
 * 
 * # Returns
 * * `Some(WorkspaceId)` - ID of the focused workspace
 * * `None` - No workspace is currently focused
 */
async workspaceGetFocus() : Promise<Result<string | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_get_focus") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the installation and update status of a plugin.
 * 
 * # Arguments
 * 
 * * `plugin_id` - Plugin identifier (e.g., "claude-code", "codex", "gemini")
 * * `check_updates` - Whether to check for available updates
 * 
 * # Returns
 * 
 * Returns `PluginStatus` with:
 * - `installed`: Whether the plugin is installed locally
 * - `installedVersion`: Version string if installed and metadata available
 * - `latestVersion`: Latest available version (if `check_updates=true` and implemented)
 * - `updateAvailable`: Whether an update is available (if `check_updates=true` and implemented)
 * - `binPath`: Path to the plugin binary if installed
 * 
 * # Errors
 * 
 * Returns `ApiError::InvalidInput` if the plugin ID is invalid.
 * Returns `ApiError::IoError` if there's a filesystem error.
 */
async pluginGetStatus(pluginId: string, checkUpdates: boolean) : Promise<Result<PluginStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_get_status", { pluginId, checkUpdates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a plugin installation operation.
 * 
 * This command initiates an async installation process:
 * 1. Validates the plugin ID
 * 2. Returns immediately with an operation ID
 * 3. Emits `acp/permission_requested` event for user approval
 * 4. On approval, installs the plugin and emits `acp/plugin_status_changed`
 * 
 * # Arguments
 * 
 * * `plugin_id` - Plugin identifier (e.g., "claude-code", "codex", "gemini")
 * * `version` - Optional version to install
 * 
 * # Returns
 * 
 * Returns `OperationStarted` with the operation ID for tracking.
 * 
 * # Errors
 * 
 * Returns `ApiError::InvalidInput` if the plugin ID is invalid.
 * Returns `ApiError::PluginInstallInProgress` if the plugin is already being installed.
 */
async pluginInstall(pluginId: string, version: string | null) : Promise<Result<OperationStarted, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_install", { pluginId, version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Respond to a pending permission request.
 * 
 * This command is called by the frontend when the user makes a decision
 * about a permission request (allow or deny).
 * 
 * # Arguments
 * 
 * * `operation_id` - The operation ID from the permission request event
 * * `decision` - The user's decision (AllowOnce or Deny)
 * 
 * # Returns
 * 
 * Ok(()) on success, or an error if the operation is not found or already resolved.
 */
async permissionRespond(operationId: string, decision: PermissionDecision) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("permission_respond", { operationId, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new agent entity within a workspace.
 * 
 * # Arguments
 * * `workspace_id` - ID of the workspace to create the agent in
 * * `plugin_id` - Plugin identifier (e.g., "claude-code", "codex", "gemini")
 * * `display_name` - Optional display name for the agent
 * 
 * # Returns
 * * `AgentSummary` - Summary of the created agent including ID
 * 
 * # Errors
 * * `ApiError::WorkspaceNotFound` - If the workspace does not exist
 * * `ApiError::InvalidInput` - If plugin_id or display_name is invalid
 */
async agentCreate(workspaceId: string, pluginId: string, displayName: string | null) : Promise<Result<AgentSummary, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_create", { workspaceId, pluginId, displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Summary of an agent returned to the frontend
 */
export type AgentSummary = { 
/**
 * Unique agent identifier
 */
agentId: string; 
/**
 * Workspace this agent belongs to
 */
workspaceId: string; 
/**
 * Plugin identifier (e.g., "claude-code", "codex", "gemini")
 */
pluginId: string; 
/**
 * Optional display name for the agent
 */
displayName: string | null }
/**
 * API errors for frontend consumption
 */
export type ApiError = 
/**
 * Invalid input parameter
 */
{ type: "invalidInput"; message: string } | 
/**
 * Path does not exist or is not accessible
 */
{ type: "pathNotFound"; path: string } | 
/**
 * Path is not a directory
 */
{ type: "pathNotDirectory"; path: string } | 
/**
 * IO error during file system operation
 */
{ type: "ioError"; message: string } | 
/**
 * Workspace not found by ID
 */
{ type: "workspaceNotFound"; workspaceId: string } | 
/**
 * Agent not found by ID
 */
{ type: "agentNotFound"; agentId: string } | 
/**
 * Operation not found by ID (e.g., permission already resolved, expired, or never existed)
 */
{ type: "operationNotFound"; operationId: string } | 
/**
 * Plugin installation is already in progress
 */
{ type: "pluginInstallInProgress"; pluginId: string }
/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Color theme name (e.g., "default", "claude")
 */
color_theme?: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Response when an async operation is started
 */
export type OperationStarted = { 
/**
 * Unique operation identifier for tracking
 */
operationId: string }
/**
 * User decision for a permission request
 */
export type PermissionDecision = 
/**
 * Allow this operation once
 */
"allowOnce" | 
/**
 * Deny this operation
 */
"deny"
/**
 * Plugin installation and update status returned to the frontend
 */
export type PluginStatus = { 
/**
 * Plugin identifier (e.g., "claude-code", "codex", "gemini")
 */
pluginId: string; 
/**
 * Whether the plugin is installed in the local cache
 */
installed: boolean; 
/**
 * Installed version string (if installed and version info available)
 */
installedVersion: string | null; 
/**
 * Latest available version (if update check was requested and succeeded)
 */
latestVersion: string | null; 
/**
 * Whether an update is available (if update check was requested)
 */
updateAvailable: boolean | null; 
/**
 * Path to the plugin binary/entry point (if installed)
 */
binPath: string | null }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Summary of a workspace returned to the frontend
 */
export type WorkspaceSummary = { 
/**
 * Unique workspace identifier
 */
workspaceId: string; 
/**
 * Canonicalized absolute path to workspace root
 */
rootDir: string; 
/**
 * Timestamp when workspace was created (milliseconds since epoch)
 * Using f64 for JavaScript number compatibility
 */
createdAtMs: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
